export interface Word {
  id: number;
  english: string;
  turkish: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
}

export const words: Word[] = [
  // A1 Level
  { id: 1, english: "Hello", turkish: "Merhaba", level: "A1" },
  { id: 2, english: "Goodbye", turkish: "Hoşça kal", level: "A1" },
  { id: 3, english: "Yes", turkish: "Evet", level: "A1" },
  { id: 4, english: "No", turkish: "Hayır", level: "A1" },
  { id: 5, english: "Thank you", turkish: "Teşekkür ederim", level: "A1" },
  { id: 6, english: "Please", turkish: "Lütfen", level: "A1" },
  { id: 7, english: "Water", turkish: "Su", level: "A1" },
  { id: 8, english: "Food", turkish: "Yemek", level: "A1" },
  { id: 9, english: "House", turkish: "Ev", level: "A1" },
  { id: 10, english: "Cat", turkish: "Kedi", level: "A1" },
  { id: 11, english: "Dog", turkish: "Köpek", level: "A1" },
  { id: 12, english: "Book", turkish: "Kitap", level: "A1" },
  { id: 13, english: "School", turkish: "Okul", level: "A1" },
  { id: 14, english: "Car", turkish: "Araba", level: "A1" },
  { id: 15, english: "Big", turkish: "Büyük", level: "A1" },
  { id: 16, english: "Small", turkish: "Küçük", level: "A1" },
  { id: 17, english: "Man", turkish: "Adam", level: "A1" },
  { id: 18, english: "Woman", turkish: "Kadın", level: "A1" },
  { id: 19, english: "Child", turkish: "Çocuk", level: "A1" },
  { id: 20, english: "Tree", turkish: "Ağaç", level: "A1" },
  { id: 21, english: "Sun", turkish: "Güneş", level: "A1" },
  { id: 22, english: "Moon", turkish: "Ay", level: "A1" },
  { id: 23, english: "Star", turkish: "Yıldız", level: "A1" },
  { id: 24, english: "Day", turkish: "Gün", level: "A1" },
  { id: 25, english: "Night", turkish: "Gece", level: "A1" },
  { id: 26, english: "Apple", turkish: "Elma", level: "A1" },
  { id: 27, english: "Banana", turkish: "Muz", level: "A1" },
  { id: 28, english: "Orange", turkish: "Portakal", level: "A1" },
  { id: 29, english: "Milk", turkish: "Süt", level: "A1" },
  { id: 30, english: "Bread", turkish: "Ekmek", level: "A1" },
  { id: 31, english: "Chair", turkish: "Sandalye", level: "A1" },
  { id: 32, english: "Table", turkish: "Masa", level: "A1" },
  { id: 33, english: "Bed", turkish: "Yatak", level: "A1" },
  { id: 34, english: "Door", turkish: "Kapı", level: "A1" },
  { id: 35, english: "Window", turkish: "Pencere", level: "A1" },
  { id: 36, english: "Pen", turkish: "Kalem", level: "A1" },
  { id: 37, english: "Pencil", turkish: "Kurşun kalem", level: "A1" },
  { id: 38, english: "Paper", turkish: "Kağıt", level: "A1" },
  { id: 39, english: "Bag", turkish: "Çanta", level: "A1" },
  { id: 40, english: "Shoe", turkish: "Ayakkabı", level: "A1" },
  { id: 41, english: "Shirt", turkish: "Gömlek", level: "A1" },
  { id: 42, english: "Hat", turkish: "Şapka", level: "A1" },
  { id: 43, english: "Ball", turkish: "Top", level: "A1" },
  { id: 44, english: "Game", turkish: "Oyun", level: "A1" },
  { id: 45, english: "Friend", turkish: "Arkadaş", level: "A1" },
  { id: 46, english: "Family", turkish: "Aile", level: "A1" },
  { id: 47, english: "Mother", turkish: "Anne", level: "A1" },
  { id: 48, english: "Father", turkish: "Baba", level: "A1" },
  { id: 49, english: "Brother", turkish: "Erkek kardeş", level: "A1" },
  { id: 50, english: "Sister", turkish: "Kız kardeş", level: "A1" },
  { id: 51, english: "Baby", turkish: "Bebek", level: "A1" },
  { id: 52, english: "Boy", turkish: "Erkek çocuk", level: "A1" },
  { id: 53, english: "Girl", turkish: "Kız çocuk", level: "A1" },
  { id: 54, english: "Teacher", turkish: "Öğretmen", level: "A1" },
  { id: 55, english: "Student", turkish: "Öğrenci", level: "A1" },
  { id: 56, english: "Doctor", turkish: "Doktor", level: "A1" },
  { id: 57, english: "Police", turkish: "Polis", level: "A1" },
  { id: 58, english: "Fire", turkish: "Ateş", level: "A1" },
  { id: 59, english: "Rain", turkish: "Yağmur", level: "A1" },
  { id: 60, english: "Snow", turkish: "Kar", level: "A1" },
  { id: 61, english: "Wind", turkish: "Rüzgar", level: "A1" },
  { id: 62, english: "Flower", turkish: "Çiçek", level: "A1" },
  { id: 63, english: "Grass", turkish: "Çimen", level: "A1" },
  { id: 64, english: "Road", turkish: "Yol", level: "A1" },
  { id: 65, english: "Bus", turkish: "Otobüs", level: "A1" },
  { id: 66, english: "Train", turkish: "Tren", level: "A1" },
  { id: 67, english: "Plane", turkish: "Uçak", level: "A1" },
  { id: 68, english: "Boat", turkish: "Tekne", level: "A1" },
  { id: 69, english: "Sea", turkish: "Deniz", level: "A1" },
  { id: 70, english: "River", turkish: "Nehir", level: "A1" },
  { id: 71, english: "Mountain", turkish: "Dağ", level: "A1" },
  { id: 72, english: "City", turkish: "Şehir", level: "A1" },
  { id: 73, english: "Village", turkish: "Köy", level: "A1" },
  { id: 74, english: "Farm", turkish: "Çiftlik", level: "A1" },
  { id: 75, english: "Animal", turkish: "Hayvan", level: "A1" },
  { id: 76, english: "Bird", turkish: "Kuş", level: "A1" },
  { id: 77, english: "Fish", turkish: "Balık", level: "A1" },
  { id: 78, english: "Horse", turkish: "At", level: "A1" },
  { id: 79, english: "Cow", turkish: "İnek", level: "A1" },
  { id: 80, english: "Sheep", turkish: "Koyun", level: "A1" },
  { id: 81, english: "Pig", turkish: "Domuz", level: "A1" },
  { id: 82, english: "Chicken", turkish: "Tavuk", level: "A1" },
  { id: 83, english: "Egg", turkish: "Yumurta", level: "A1" },
  { id: 84, english: "Color", turkish: "Renk", level: "A1" },
  { id: 85, english: "Red", turkish: "Kırmızı", level: "A1" },
  { id: 86, english: "Blue", turkish: "Mavi", level: "A1" },
  { id: 87, english: "Green", turkish: "Yeşil", level: "A1" },
  { id: 88, english: "Yellow", turkish: "Sarı", level: "A1" },
  { id: 89, english: "Black", turkish: "Siyah", level: "A1" },
  { id: 90, english: "White", turkish: "Beyaz", level: "A1" },
  { id: 91, english: "Number", turkish: "Sayı", level: "A1" },
  { id: 92, english: "One", turkish: "Bir", level: "A1" },
  { id: 93, english: "Two", turkish: "İki", level: "A1" },
  { id: 94, english: "Three", turkish: "Üç", level: "A1" },
  { id: 95, english: "Four", turkish: "Dört", level: "A1" },
  { id: 96, english: "Five", turkish: "Beş", level: "A1" },
  { id: 97, english: "Happy", turkish: "Mutlu", level: "A1" },
  { id: 98, english: "Sad", turkish: "Üzgün", level: "A1" },
  { id: 99, english: "Good", turkish: "İyi", level: "A1" },
  { id: 100, english: "Bad", turkish: "Kötü", level: "A1" },

  // A2 Level
  { id: 101, english: "Always", turkish: "Her zaman", level: "A2" },
  { id: 102, english: "Sometimes", turkish: "Bazen", level: "A2" },
  { id: 103, english: "Never", turkish: "Asla", level: "A2" },
  { id: 104, english: "Often", turkish: "Sık sık", level: "A2" },
  { id: 105, english: "Usually", turkish: "Genellikle", level: "A2" },
  { id: 106, english: "Early", turkish: "Erken", level: "A2" },
  { id: 107, english: "Late", turkish: "Geç", level: "A2" },
  { id: 108, english: "Quickly", turkish: "Hızlıca", level: "A2" },
  { id: 109, english: "Slowly", turkish: "Yavaşça", level: "A2" },
  { id: 110, english: "Carefully", turkish: "Dikkatlice", level: "A2" },
  { id: 111, english: "Easily", turkish: "Kolayca", level: "A2" },
  { id: 112, english: "Loudly", turkish: "Yüksek sesle", level: "A2" },
  { id: 113, english: "Quietly", turkish: "Sessizce", level: "A2" },
  { id: 114, english: "Together", turkish: "Birlikte", level: "A2" },
  { id: 115, english: "Alone", turkish: "Yalnız", level: "A2" },
  { id: 116, english: "Holiday", turkish: "Tatil", level: "A2" },
  { id: 117, english: "Weekend", turkish: "Hafta sonu", level: "A2" },
  { id: 118, english: "Month", turkish: "Ay (zaman)", level: "A2" },
  { id: 119, english: "Year", turkish: "Yıl", level: "A2" },
  { id: 120, english: "Season", turkish: "Mevsim", level: "A2" },
  { id: 121, english: "Spring", turkish: "İlkbahar", level: "A2" },
  { id: 122, english: "Summer", turkish: "Yaz", level: "A2" },
  { id: 123, english: "Autumn", turkish: "Sonbahar", level: "A2" },
  { id: 124, english: "Winter", turkish: "Kış", level: "A2" },
  { id: 125, english: "Weather", turkish: "Hava durumu", level: "A2" },
  { id: 126, english: "Sunny", turkish: "Güneşli", level: "A2" },
  { id: 127, english: "Cloudy", turkish: "Bulutlu", level: "A2" },
  { id: 128, english: "Rainy", turkish: "Yağmurlu", level: "A2" },
  { id: 129, english: "Snowy", turkish: "Karlı", level: "A2" },
  { id: 130, english: "Windy", turkish: "Rüzgarlı", level: "A2" },
  { id: 131, english: "Hot", turkish: "Sıcak", level: "A2" },
  { id: 132, english: "Cold", turkish: "Soğuk", level: "A2" },
  { id: 133, english: "Warm", turkish: "Ilık", level: "A2" },
  { id: 134, english: "Cool", turkish: "Serin", level: "A2" },
  { id: 135, english: "Clothes", turkish: "Kıyafetler", level: "A2" },
  { id: 136, english: "Trousers", turkish: "Pantolon", level: "A2" },
  { id: 137, english: "Dress", turkish: "Elbise", level: "A2" },
  { id: 138, english: "Skirt", turkish: "Etek", level: "A2" },
  { id: 139, english: "Jacket", turkish: "Ceket", level: "A2" },
  { id: 140, english: "Coat", turkish: "Palto", level: "A2" },
  { id: 141, english: "Socks", turkish: "Çorap", level: "A2" },
  { id: 142, english: "Shoes", turkish: "Ayakkabılar", level: "A2" },
  { id: 143, english: "Watch", turkish: "Saat (kol)", level: "A2" },
  { id: 144, english: "Glasses", turkish: "Gözlük", level: "A2" },
  { id: 145, english: "Money", turkish: "Para", level: "A2" },
  { id: 146, english: "Price", turkish: "Fiyat", level: "A2" },
  { id: 147, english: "Shop", turkish: "Dükkan / Alışveriş yapmak", level: "A2" },
  { id: 148, english: "Market", turkish: "Pazar", level: "A2" },
  { id: 149, english: "Buy", turkish: "Satın almak", level: "A2" },
  { id: 150, english: "Sell", turkish: "Satmak", level: "A2" },
  { id: 151, english: "Pay", turkish: "Ödemek", level: "A2" },
  { id: 152, english: "Expensive", turkish: "Pahalı", level: "A2" },
  { id: 153, english: "Cheap", turkish: "Ucuz", level: "A2" },
  { id: 154, english: "Free", turkish: "Bedava / Özgür", level: "A2" },
  { id: 155, english: "Hobby", turkish: "Hobi", level: "A2" },
  { id: 156, english: "Music", turkish: "Müzik", level: "A2" },
  { id: 157, english: "Song", turkish: "Şarkı", level: "A2" },
  { id: 158, english: "Dance", turkish: "Dans / Dans etmek", level: "A2" },
  { id: 159, english: "Sport", turkish: "Spor", level: "A2" },
  { id: 160, english: "Team", turkish: "Takım", level: "A2" },
  { id: 161, english: "Player", turkish: "Oyuncu", level: "A2" },
  { id: 162, english: "Read", turkish: "Okumak", level: "A2" },
  { id: 163, english: "Write", turkish: "Yazmak", level: "A2" },
  { id: 164, english: "Speak", turkish: "Konuşmak", level: "A2" },
  { id: 165, english: "Listen", turkish: "Dinlemek", level: "A2" },
  { id: 166, english: "Learn", turkish: "Öğrenmek", level: "A2" },
  { id: 167, english: "Study", turkish: "Ders çalışmak", level: "A2" },
  { id: 168, english: "Know", turkish: "Bilmek", level: "A2" },
  { id: 169, english: "Think", turkish: "Düşünmek", level: "A2" },
  { id: 170, english: "Want", turkish: "İstemek", level: "A2" },
  { id: 171, english: "Need", turkish: "İhtiyaç duymak", level: "A2" },
  { id: 172, english: "Like", turkish: "Beğenmek / Gibi", level: "A2" },
  { id: 173, english: "Love", turkish: "Sevmek / Aşk", level: "A2" },
  { id: 174, english: "Hate", turkish: "Nefret etmek", level: "A2" },
  { id: 175, english: "Help", turkish: "Yardım etmek / Yardım", level: "A2" },
  { id: 176, english: "Use", turkish: "Kullanmak", level: "A2" },
  { id: 177, english: "Find", turkish: "Bulmak", level: "A2" },
  { id: 178, english: "Give", turkish: "Vermek", level: "A2" },
  { id: 179, english: "Take", turkish: "Almak", level: "A2" },
  { id: 180, english: "Make", turkish: "Yapmak (oluşturmak)", level: "A2" },
  { id: 181, english: "Do", turkish: "Yapmak (eylem)", level: "A2" },
  { id: 182, english: "Go", turkish: "Gitmek", level: "A2" },
  { id: 183, english: "Come", turkish: "Gelmek", level: "A2" },
  { id: 184, english: "See", turkish: "Görmek", level: "A2" },
  { id: 185, english: "Look", turkish: "Bakmak", level: "A2" },
  { id: 186, english: "Eat", turkish: "Yemek yemek", level: "A2" },
  { id: 187, english: "Drink", turkish: "İçmek", level: "A2" },
  { id: 188, english: "Sleep", turkish: "Uyumak", level: "A2" },
  { id: 189, english: "Wake up", turkish: "Uyanmak", level: "A2" },
  { id: 190, english: "Sit", turkish: "Oturmak", level: "A2" },
  { id: 191, english: "Stand", turkish: "Ayakta durmak", level: "A2" },
  { id: 192, english: "Walk", turkish: "Yürümek", level: "A2" },
  { id: 193, english: "Run", turkish: "Koşmak", level: "A2" },
  { id: 194, english: "Swim", turkish: "Yüzmek", level: "A2" },
  { id: 195, english: "Drive", turkish: "Sürmek (araç)", level: "A2" },
  { id: 196, english: "Fly", turkish: "Uçmak", level: "A2" },
  { id: 197, english: "Travel", turkish: "Seyahat etmek", level: "A2" },
  { id: 198, english: "Visit", turkish: "Ziyaret etmek", level: "A2" },
  { id: 199, english: "Meet", turkish: "Tanışmak / Buluşmak", level: "A2" },
  { id: 200, english: "Talk", turkish: "Konuşmak (sohbet)", level: "A2" },

  // B1 Level
  { id: 201, english: "Ability", turkish: "Yetenek", level: "B1" },
  { id: 202, english: "Abroad", turkish: "Yurt dışı", level: "B1" },
  { id: 203, english: "Accept", turkish: "Kabul etmek", level: "B1" },
  { id: 204, english: "Accident", turkish: "Kaza", level: "B1" },
  { id: 205, english: "Achieve", turkish: "Başarmak", level: "B1" },
  { id: 206, english: "Activity", turkish: "Aktivite", level: "B1" },
  { id: 207, english: "Adult", turkish: "Yetişkin", level: "B1" },
  { id: 208, english: "Advantage", turkish: "Avantaj", level: "B1" },
  { id: 209, english: "Adventure", turkish: "Macera", level: "B1" },
  { id: 210, english: "Advice", turkish: "Tavsiye", level: "B1" },
  { id: 211, english: "Afraid", turkish: "Korkmuş", level: "B1" },
  { id: 212, english: "Agree", turkish: "Aynı fikirde olmak", level: "B1" },
  { id: 213, english: "Aim", turkish: "Amaç / Hedeflemek", level: "B1" },
  { id: 214, english: "Allow", turkish: "İzin vermek", level: "B1" },
  { id: 215, english: "Almost", turkish: "Neredeyse", level: "B1" },
  { id: 216, english: "Amazing", turkish: "Harika", level: "B1" },
  { id: 217, english: "Angry", turkish: "Kızgın", level: "B1" },
  { id: 218, english: "Announce", turkish: "Duyurmak", level: "B1" },
  { id: 219, english: "Anxious", turkish: "Endişeli", level: "B1" },
  { id: 220, english: "Apologize", turkish: "Özür dilemek", level: "B1" },
  { id: 221, english: "Appear", turkish: "Görünmek / Ortaya çıkmak", level: "B1" },
  { id: 222, english: "Apply", turkish: "Başvurmak / Uygulamak", level: "B1" },
  { id: 223, english: "Argue", turkish: "Tartışmak", level: "B1" },
  { id: 224, english: "Arrange", turkish: "Düzenlemek", level: "B1" },
  { id: 225, english: "Arrive", turkish: "Varmak", level: "B1" },
  { id: 226, english: "Article", turkish: "Makale / Eşya", level: "B1" },
  { id: 227, english: "Artist", turkish: "Sanatçı", level: "B1" },
  { id: 228, english: "Ashamed", turkish: "Utanmış", level: "B1" },
  { id: 229, english: "Ask", turkish: "Sormak / İstemek", level: "B1" },
  { id: 230, english: "Attend", turkish: "Katılmak (bir etkinliğe)", level: "B1" },
  { id: 231, english: "Attitude", turkish: "Tutum / Davranış", level: "B1" },
  { id: 232, english: "Audience", turkish: "Seyirci / Dinleyici", level: "B1" },
  { id: 233, english: "Average", turkish: "Ortalama", level: "B1" },
  { id: 234, english: "Avoid", turkish: "Kaçınmak", level: "B1" },
  { id: 235, english: "Award", turkish: "Ödül", level: "B1" },
  { id: 236, english: "Aware", turkish: "Farkında", level: "B1" },
  { id: 237, english: "Awful", turkish: "Berbat", level: "B1" },
  { id: 238, english: "Balance", turkish: "Denge", level: "B1" },
  { id: 239, english: "Band", turkish: "Müzik grubu / Şerit", level: "B1" },
  { id: 240, english: "Basic", turkish: "Temel", level: "B1" },
  { id: 241, english: "Battle", turkish: "Savaş / Mücadele", level: "B1" },
  { id: 242, english: "Beach", turkish: "Plaj", level: "B1" },
  { id: 243, english: "Beautiful", turkish: "Güzel", level: "B1" },
  { id: 244, english: "Become", turkish: "Olmak / Haline gelmek", level: "B1" },
  { id: 245, english: "Begin", turkish: "Başlamak", level: "B1" },
  { id: 246, english: "Behave", turkish: "Davranmak", level: "B1" },
  { id: 247, english: "Believe", turkish: "İnanmak", level: "B1" },
  { id: 248, english: "Belong", turkish: "Ait olmak", level: "B1" },
  { id: 249, english: "Benefit", turkish: "Fayda / Yarar", level: "B1" },
  { id: 250, english: "Bicycle", turkish: "Bisiklet", level: "B1" },
  { id: 251, english: "Billion", turkish: "Milyar", level: "B1" },
  { id: 252, english: "Blame", turkish: "Suçlamak", level: "B1" },
  { id: 253, english: "Blanket", turkish: "Battaniye", level: "B1" },
  { id: 254, english: "Blood", turkish: "Kan", level: "B1" },
  { id: 255, english: "Board", turkish: "Tahta / Kurul", level: "B1" },
  { id: 256, english: "Boil", turkish: "Kaynamak / Kaynatmak", level: "B1" },
  { id: 257, english: "Bone", turkish: "Kemik", level: "B1" },
  { id: 258, english: "Boring", turkish: "Sıkıcı", level: "B1" },
  { id: 259, english: "Borrow", turkish: "Ödünç almak", level: "B1" },
  { id: 260, english: "Boss", turkish: "Patron", level: "B1" },
  { id: 261, english: "Bother", turkish: "Rahatsız etmek", level: "B1" },
  { id: 262, english: "Bottle", turkish: "Şişe", level: "B1" },
  { id: 263, english: "Bottom", turkish: "Alt / Dip", level: "B1" },
  { id: 264, english: "Brain", turkish: "Beyin", level: "B1" },
  { id: 265, english: "Brave", turkish: "Cesur", level: "B1" },
  { id: 266, english: "Break", turkish: "Kırmak / Mola", level: "B1" },
  { id: 267, english: "Breakfast", turkish: "Kahvaltı", level: "B1" },
  { id: 268, english: "Bridge", turkish: "Köprü", level: "B1" },
  { id: 269, english: "Bright", turkish: "Parlak / Zeki", level: "B1" },
  { id: 270, english: "Bring", turkish: "Getirmek", level: "B1" },
  { id: 271, english: "Build", turkish: "İnşa etmek", level: "B1" },
  { id: 272, english: "Busy", turkish: "Meşgul", level: "B1" },
  { id: 273, english: "Business", turkish: "İş / Ticaret", level: "B1" },
  { id: 274, english: "Button", turkish: "Düğme", level: "B1" },
  { id: 275, english: "Calendar", turkish: "Takvim", level: "B1" },
  { id: 276, english: "Call", turkish: "Aramak / Çağırmak", level: "B1" },
  { id: 277, english: "Calm", turkish: "Sakin", level: "B1" },
  { id: 278, english: "Camera", turkish: "Kamera", level: "B1" },
  { id: 279, english: "Camp", turkish: "Kamp / Kamp yapmak", level: "B1" },
  { id: 280, english: "Cancel", turkish: "İptal etmek", level: "B1" },
  { id: 281, english: "Candidate", turkish: "Aday", level: "B1" },
  { id: 282, english: "Capital", turkish: "Başkent / Sermaye", level: "B1" },
  { id: 283, english: "Career", turkish: "Kariyer", level: "B1" },
  { id: 284, english: "Careful", turkish: "Dikkatli", level: "B1" },
  { id: 285, english: "Carry", turkish: "Taşımak", level: "B1" },
  { id: 286, english: "Case", turkish: "Durum / Dava / Kutu", level: "B1" },
  { id: 287, english: "Cash", turkish: "Nakit para", level: "B1" },
  { id: 288, english: "Catch", turkish: "Yakalamak", level: "B1" },
  { id: 289, english: "Cause", turkish: "Neden / Sebep olmak", level: "B1" },
  { id: 290, english: "Celebrate", turkish: "Kutlamak", level: "B1" },
  { id: 291, english: "Century", turkish: "Yüzyıl", level: "B1" },
  { id: 292, english: "Certain", turkish: "Kesin / Belirli", level: "B1" },
  { id: 293, english: "Challenge", turkish: "Meydan okuma / Zorluk", level: "B1" },
  { id: 294, english: "Chance", turkish: "Şans / Fırsat", level: "B1" },
  { id: 295, english: "Change", turkish: "Değiştirmek / Değişiklik", level: "B1" },
  { id: 296, english: "Character", turkish: "Karakter / Kişilik", level: "B1" },
  { id: 297, english: "Charge", turkish: "Şarj etmek / Ücret / Suçlama", level: "B1" },
  { id: 298, english: "Chat", turkish: "Sohbet etmek", level: "B1" },
  { id: 299, english: "Check", turkish: "Kontrol etmek / Hesap", level: "B1" },
  { id: 300, english: "Choice", turkish: "Seçim", level: "B1" },

  // B2 Level
  { id: 301, english: "Abandon", turkish: "Terk etmek", level: "B2" },
  { id: 302, english: "Absolute", turkish: "Mutlak / Kesin", level: "B2" },
  { id: 303, english: "Absorb", turkish: "Emmek / Soğurmak", level: "B2" },
  { id: 304, english: "Abstract", turkish: "Soyut / Özet", level: "B2" },
  { id: 305, english: "Academic", turkish: "Akademik", level: "B2" },
  { id: 306, english: "Accent", turkish: "Aksan / Vurgu", level: "B2" },
  { id: 307, english: "Access", turkish: "Erişim / Erişmek", level: "B2" },
  { id: 308, english: "Accompany", turkish: "Eşlik etmek", level: "B2" },
  { id: 309, english: "Account", turkish: "Hesap / Açıklama", level: "B2" },
  { id: 310, english: "Accurate", turkish: "Doğru / Kesin", level: "B2" },
  { id: 311, english: "Accuse", turkish: "Suçlamak", level: "B2" },
  { id: 312, english: "Acknowledge", turkish: "Kabul etmek / Tanımak", level: "B2" },
  { id: 313, english: "Acquire", turkish: "Edinmek / Kazanmak", level: "B2" },
  { id: 314, english: "Adapt", turkish: "Uyum sağlamak / Uyarlamak", level: "B2" },
  { id: 315, english: "Additional", turkish: "Ek / İlave", level: "B2" },
  { id: 316, english: "Address", turkish: "Adres / Hitap etmek / Ele almak", level: "B2" },
  { id: 317, english: "Adjust", turkish: "Ayarlamak", level: "B2" },
  { id: 318, english: "Administration", turkish: "Yönetim / İdare", level: "B2" },
  { id: 319, english: "Admire", turkish: "Hayran olmak", level: "B2" },
  { id: 320, english: "Admit", turkish: "İtiraf etmek / Kabul etmek", level: "B2" },
  { id: 321, english: "Adopt", turkish: "Evlat edinmek / Benimsemek", level: "B2" },
  { id: 322, english: "Advance", turkish: "İlerlemek / Gelişmek", level: "B2" },
  { id: 323, english: "Affair", turkish: "Mesele / İlişki", level: "B2" },
  { id: 324, english: "Affect", turkish: "Etkilemek", level: "B2" },
  { id: 325, english: "Afford", turkish: "Parası yetmek / Gücü yetmek", level: "B2" },
  { id: 326, english: "Agency", turkish: "Ajans / Kurum", level: "B2" },
  { id: 327, english: "Agenda", turkish: "Gündem", level: "B2" },
  { id: 328, english: "Aggressive", turkish: "Agresif / Saldırgan", level: "B2" },
  { id: 329, english: "Aid", turkish: "Yardım / Yardım etmek", level: "B2" },
  { id: 330, english: "Alarm", turkish: "Alarm / Telaşlandırmak", level: "B2" },
  { id: 331, english: "Alter", turkish: "Değiştirmek", level: "B2" },
  { id: 332, english: "Alternative", turkish: "Alternatif / Seçenek", level: "B2" },
  { id: 333, english: "Amount", turkish: "Miktar", level: "B2" },
  { id: 334, english: "Analysis", turkish: "Analiz", level: "B2" },
  { id: 335, english: "Ancient", turkish: "Antik / Eski", level: "B2" },
  { id: 336, english: "Angle", turkish: "Açı / Bakış açısı", level: "B2" },
  { id: 337, english: "Annual", turkish: "Yıllık", level: "B2" },
  { id: 338, english: "Anticipate", turkish: "Beklemek / Ummak", level: "B2" },
  { id: 339, english: "Anxiety", turkish: "Kaygı / Endişe", level: "B2" },
  { id: 340, english: "Apparently", turkish: "Görünüşe göre", level: "B2" },
  { id: 341, english: "Appeal", turkish: "Cazibe / Başvuru / Çağrı", level: "B2" },
  { id: 342, english: "Approach", turkish: "Yaklaşım / Yaklaşmak", level: "B2" },
  { id: 343, english: "Appropriate", turkish: "Uygun", level: "B2" },
  { id: 344, english: "Approval", turkish: "Onay", level: "B2" },
  { id: 345, english: "Approve", turkish: "Onaylamak", level: "B2" },
  { id: 346, english: "Approximately", turkish: "Yaklaşık olarak", level: "B2" },
  { id: 347, english: "Architect", turkish: "Mimar", level: "B2" },
  { id: 348, english: "Argument", turkish: "Tartışma / Argüman", level: "B2" },
  { id: 349, english: "Arise", turkish: "Ortaya çıkmak / Yükselmek", level: "B2" },
  { id: 350, english: "Armed", turkish: "Silahlı", level: "B2" },
  { id: 351, english: "Arrow", turkish: "Ok", level: "B2" },
  { id: 352, english: "Artificial", turkish: "Yapay", level: "B2" },
  { id: 353, english: "Aspect", turkish: "Yön / Özellik", level: "B2" },
  { id: 354, english: "Assault", turkish: "Saldırı / Saldırmak", level: "B2" },
  { id: 355, english: "Assemble", turkish: "Bir araya getirmek / Monte etmek", level: "B2" },
  { id: 356, english: "Assess", turkish: "Değerlendirmek", level: "B2" },
  { id: 357, english: "Assign", turkish: "Atamak / Görevlendirmek", level: "B2" },
  { id: 358, english: "Assist", turkish: "Yardım etmek", level: "B2" },
  { id: 359, english: "Associate", turkish: "İlişkilendirmek / Ortak", level: "B2" },
  { id: 360, english: "Assume", turkish: "Varsaymak / Üstlenmek", level: "B2" },
  { id: 361, english: "Assure", turkish: "Garanti etmek / Temin etmek", level: "B2" },
  { id: 362, english: "Atmosphere", turkish: "Atmosfer / Ortam", level: "B2" },
  { id: 363, english: "Attach", turkish: "Eklemek / Bağlamak", level: "B2" },
  { id: 364, english: "Attempt", turkish: "Girişim / Teşebbüs etmek", level: "B2" },
  { id: 365, english: "Attract", turkish: "Cezbetmek / Çekmek", level: "B2" },
  { id: 366, english: "Attribute", turkish: "Atfetmek / Nitelik", level: "B2" },
  { id: 367, english: "Authority", turkish: "Otorite / Yetki", level: "B2" },
  { id: 368, english: "Available", turkish: "Mevcut / Uygun", level: "B2" },
  { id: 369, english: "Background", turkish: "Arka plan / Geçmiş", level: "B2" },
  { id: 370, english: "Barrier", turkish: "Engel / Bariyer", level: "B2" },
  { id: 371, english: "Basis", turkish: "Temel / Esas", level: "B2" },
  { id: 372, english: "Behavior", turkish: "Davranış", level: "B2" },
  { id: 373, english: "Belief", turkish: "İnanç", level: "B2" },
  { id: 374, english: "Bend", turkish: "Eğmek / Bükmek", level: "B2" },
  { id: 375, english: "Bias", turkish: "Önyargı", level: "B2" },
  { id: 376, english: "Bid", turkish: "Teklif / Teklif vermek (ihale)", level: "B2" },
  { id: 377, english: "Bind", turkish: "Bağlamak / Ciltlemek", level: "B2" },
  { id: 378, english: "Biological", turkish: "Biyolojik", level: "B2" },
  { id: 379, english: "Blame (noun)", turkish: "Suç", level: "B2" },
  { id: 380, english: "Bomb", turkish: "Bomba / Bombalamak", level: "B2" },
  { id: 381, english: "Bond", turkish: "Bağ / Tahvil", level: "B2" },
  { id: 382, english: "Border", turkish: "Sınır", level: "B2" },
  { id: 383, english: "Branch", turkish: "Dal / Şube", level: "B2" },
  { id: 384, english: "Brand", turkish: "Marka", level: "B2" },
  { id: 385, english: "Brief", turkish: "Kısa / Özet", level: "B2" },
  { id: 386, english: "Budget", turkish: "Bütçe", level: "B2" },
  { id: 387, english: "Burden", turkish: "Yük", level: "B2" },
  { id: 388, english: "Campaign", turkish: "Kampanya", level: "B2" },
  { id: 389, english: "Capacity", turkish: "Kapasite", level: "B2" },
  { id: 390, english: "Capture", turkish: "Ele geçirmek / Yakalamak", level: "B2" },
  { id: 391, english: "Cast", turkish: "Rol vermek / Alçı / Oyuncular", level: "B2" },
  { id: 392, english: "Category", turkish: "Kategori", level: "B2" },
  { id: 393, english: "Cease", turkish: "Durdurmak / Sona ermek", level: "B2" },
  { id: 394, english: "Challenge (verb)", turkish: "Meydan okumak", level: "B2" },
  { id: 395, english: "Channel", turkish: "Kanal", level: "B2" },
  { id: 396, english: "Chapter", turkish: "Bölüm (kitap)", level: "B2" },
  { id: 397, english: "Characteristic", turkish: "Karakteristik / Özellik", level: "B2" },
  { id: 398, english: "Chart", turkish: "Grafik / Harita", level: "B2" },
  { id: 399, english: "Chief", turkish: "Şef / Başlıca", level: "B2" },
  { id: 400, english: "Circumstance", turkish: "Durum / Koşul", level: "B2" },

  // C1 Level
  { id: 401, english: "Abundant", turkish: "Bol / Bereketli", level: "C1" },
  { id: 402, english: "Accelerate", turkish: "Hızlandırmak", level: "C1" },
  { id: 403, english: "Accommodate", turkish: "Yerleştirmek / Uyum sağlamak", level: "C1" },
  { id: 404, english: "Accumulate", turkish: "Biriktirmek / Toplamak", level: "C1" },
  { id: 405, english: "Acquisition", turkish: "Edinme / Kazanım", level: "C1" },
  { id: 406, english: "Adequate", turkish: "Yeterli", level: "C1" },
  { id: 407, english: "Adjacent", turkish: "Bitişik / Komşu", level: "C1" },
  { id: 408, english: "Advocate", turkish: "Savunmak / Avukat", level: "C1" },
  { id: 409, english: "Affluent", turkish: "Varlıklı / Zengin", level: "C1" },
  { id: 410, english: "Aggregate", turkish: "Toplam / Bir araya getirmek", level: "C1" },
  { id: 411, english: "Albeit", turkish: "Rağmen / Her ne kadar", level: "C1" },
  { id: 412, english: "Allocate", turkish: "Tahsis etmek / Ayırmak", level: "C1" },
  { id: 413, english: "Ambiguous", turkish: "Belirsiz / Muğlak", level: "C1" },
  { id: 414, english: "Amend", turkish: "Değiştirmek / Düzeltmek (yasa)", level: "C1" },
  { id: 415, english: "Analogy", turkish: "Benzetme / Analoji", level: "C1" },
  { id: 416, english: "Annihilate", turkish: "Yok etmek / İmha etmek", level: "C1" },
  { id: 417, english: "Apparent", turkish: "Açık / Belli", level: "C1" },
  { id: 418, english: "Appreciate", turkish: "Takdir etmek / Değerini bilmek", level: "C1" },
  { id: 419, english: "Arbitrary", turkish: "Keyfi / Rastgele", level: "C1" },
  { id: 420, english: "Articulate", turkish: "Açıkça ifade etmek / Anlaşılır konuşan", level: "C1" },
  { id: 421, english: "Aspiration", turkish: "Arzu / İstek", level: "C1" },
  { id: 422, english: "Assert", turkish: "İddia etmek / Savunmak", level: "C1" },
  { id: 423, english: "Attain", turkish: "Elde etmek / Ulaşmak", level: "C1" },
  { id: 424, english: "Augment", turkish: "Artırmak / Çoğaltmak", level: "C1" },
  { id: 425, english: "Authentic", turkish: "Otantik / Gerçek", level: "C1" },
  { id: 426, english: "Autonomous", turkish: "Özerk / Bağımsız", level: "C1" },
  { id: 427, english: "Benchmark", turkish: "Kıyaslama noktası / Ölçüt", level: "C1" },
  { id: 428, english: "Beneficial", turkish: "Faydalı / Yararlı", level: "C1" },
  { id: 429, english: "Benign", turkish: "İyi huylu / Zararsız", level: "C1" },
  { id: 430, english: "Bolster", turkish: "Desteklemek / Güçlendirmek", level: "C1" },
  { id: 431, english: "Breakthrough", turkish: "Büyük buluş / Atılım", level: "C1" },
  { id: 432, english: "Bureaucracy", turkish: "Bürokrasi", level: "C1" },
  { id: 433, english: "Candid", turkish: "Samimi / İçten", level: "C1" },
  { id: 434, english: "Catalyst", turkish: "Katalizör / Hızlandırıcı etken", level: "C1" },
  { id: 435, english: "Chronic", turkish: "Kronik / Sürekli", level: "C1" },
  { id: 436, english: "Clarify", turkish: "Açıklığa kavuşturmak", level: "C1" },
  { id: 437, english: "Coherent", turkish: "Tutarlı / Uyumlu", level: "C1" },
  { id: 438, english: "Coincide", turkish: "Tesadüf etmek / Aynı zamana denk gelmek", level: "C1" },
  { id: 439, english: "Collaborate", turkish: "İşbirliği yapmak", level: "C1" },
  { id: 440, english: "Commence", turkish: "Başlamak", level: "C1" },
  { id: 441, english: "Compatible", turkish: "Uyumlu", level: "C1" },
  { id: 442, english: "Compel", turkish: "Zorlamak / Mecbur etmek", level: "C1" },
  { id: 443, english: "Compensate", turkish: "Tazmin etmek / Telafi etmek", level: "C1" },
  { id: 444, english: "Competent", turkish: "Yetkin / Ehil", level: "C1" },
  { id: 445, english: "Compile", turkish: "Derlemek / Toplamak", level: "C1" },
  { id: 446, english: "Complement", turkish: "Tamamlamak / Bütünlemek", level: "C1" },
  { id: 447, english: "Complex", turkish: "Karmaşık", level: "C1" },
  { id: 448, english: "Component", turkish: "Bileşen / Parça", level: "C1" },
  { id: 449, english: "Comprehend", turkish: "Anlamak / Kavramak", level: "C1" },
  { id: 450, english: "Comprehensive", turkish: "Kapsamlı", level: "C1" },
  { id: 451, english: "Concede", turkish: "Kabul etmek (yenilgiyi vb.)", level: "C1" },
  { id: 452, english: "Conceive", turkish: "Tasarlamak / Gebe kalmak", level: "C1" },
  { id: 453, english: "Concentrate", turkish: "Konsantre olmak / Yoğunlaşmak", level: "C1" },
  { id: 454, english: "Concise", turkish: "Kısa ve öz", level: "C1" },
  { id: 455, english: "Concur", turkish: "Aynı fikirde olmak", level: "C1" },
  { id: 456, english: "Condemn", turkish: "Kınamak / Mahkum etmek", level: "C1" },
  { id: 457, english: "Confer", turkish: "Görüşmek / Vermek (unvan vb.)", level: "C1" },
  { id: 458, english: "Confine", turkish: "Sınırlamak / Hapsetmek", level: "C1" },
  { id: 459, english: "Confirm", turkish: "Doğrulamak / Onaylamak", level: "C1" },
  { id: 460, english: "Conflict", turkish: "Çatışma / Anlaşmazlık", level: "C1" },
  { id: 461, english: "Conform", turkish: "Uymak / Boyun eğmek", level: "C1" },
  { id: 462, english: "Confront", turkish: "Yüzleşmek / Karşı koymak", level: "C1" },
  { id: 463, english: "Congestion", turkish: "Tıkanıklık / Kalabalık", level: "C1" },
  { id: 464, english: "Conscious", turkish: "Bilinçli", level: "C1" },
  { id: 465, english: "Consensus", turkish: "Fikir birliği / Uzlaşma", level: "C1" },
  { id: 466, english: "Consent", turkish: "Rıza / Onay", level: "C1" },
  { id: 467, english: "Consequent", turkish: "Sonuç olarak ortaya çıkan", level: "C1" },
  { id: 468, english: "Considerable", turkish: "Önemli miktarda / Hatırı sayılır", level: "C1" },
  { id: 469, english: "Consistent", turkish: "Tutarlı / İstikrarlı", level: "C1" },
  { id: 470, english: "Consolidate", turkish: "Sağlamlaştırmak / Birleştirmek", level: "C1" },
  { id: 471, english: "Constitute", turkish: "Oluşturmak / Teşkil etmek", level: "C1" },
  { id: 472, english: "Constrain", turkish: "Kısıtlamak / Zorlamak", level: "C1" },
  { id: 473, english: "Consult", turkish: "Danışmak", level: "C1" },
  { id: 474, english: "Consume", turkish: "Tüketmek", level: "C1" },
  { id: 475, english: "Contemplate", turkish: "Derin düşünmek / Tasarlamak", level: "C1" },
  { id: 476, english: "Contemporary", turkish: "Çağdaş / Modern", level: "C1" },
  { id: 477, english: "Contend", turkish: "İddia etmek / Mücadele etmek", level: "C1" },
  { id: 478, english: "Context", turkish: "Bağlam / Durum", level: "C1" },
  { id: 479, english: "Contradict", turkish: "Çelişmek / Aksini iddia etmek", level: "C1" },
  { id: 480, english: "Contribute", turkish: "Katkıda bulunmak", level: "C1" },
  { id: 481, english: "Controversial", turkish: "Tartışmalı", level: "C1" },
  { id: 482, english: "Convene", turkish: "Toplanmak / Toplantıya çağırmak", level: "C1" },
  { id: 483, english: "Conventional", turkish: "Geleneksel / Alışılmış", level: "C1" },
  { id: 484, english: "Converge", turkish: "Yakınsamak / Birleşmek", level: "C1" },
  { id: 485, english: "Converse", turkish: "Konuşmak / Sohbet etmek", level: "C1" },
  { id: 486, english: "Convert", turkish: "Dönüştürmek", level: "C1" },
  { id: 487, english: "Convey", turkish: "İletmek / Taşımak", level: "C1" },
  { id: 488, english: "Convict", turkish: "Mahkum etmek / Suçlu", level: "C1" },
  { id: 489, english: "Convince", turkish: "İkna etmek", level: "C1" },
  { id: 490, english: "Cooperate", turkish: "İşbirliği yapmak", level: "C1" },
  { id: 491, english: "Coordinate", turkish: "Koordine etmek / Eşgüdüm sağlamak", level: "C1" },
  { id: 492, english: "Core", turkish: "Çekirdek / Öz", level: "C1" },
  { id: 493, english: "Correlate", turkish: "İlişkilendirmek / Bağlantı kurmak", level: "C1" },
  { id: 494, english: "Correspond", turkish: "Tekabül etmek / Haberleşmek", level: "C1" },
  { id: 495, english: "Corrupt", turkish: "Yozlaşmış / Rüşvetçi", level: "C1" },
  { id: 496, english: "Credible", turkish: "İnanılır / Güvenilir", level: "C1" },
  { id: 497, english: "Criterion", turkish: "Kriter / Ölçüt", level: "C1" },
  { id: 498, english: "Crucial", turkish: "Çok önemli / Hayati", level: "C1" },
  { id: 499, english: "Culminate", turkish: "Sonuçlanmak / Doruğa ulaşmak", level: "C1" },
  { id: 500, english: "Cultivate", turkish: "Yetiştirmek / Geliştirmek", level: "C1" },

  // C2 Level
  { id: 501, english: "Aberration", turkish: "Sapma / Anormallik", level: "C2" },
  { id: 502, english: "Abhor", turkish: "Nefret etmek / Tiksinmek", level: "C2" },
  { id: 503, english: "Abject", turkish: "Sefil / Perişan", level: "C2" },
  { id: 504, english: "Abnegation", turkish: "Feragat / Vazgeçme", level: "C2" },
  { id: 505, english: "Abridge", turkish: "Kısaltmak / Özetlemek", level: "C2" },
  { id: 506, english: "Abstruse", turkish: "Anlaşılması güç / Derin", level: "C2" },
  { id: 507, english: "Acrimonious", turkish: "Sert / Kırıcı (dil, tartışma)", level: "C2" },
  { id: 508, english: "Adamant", turkish: "İnatçı / Kararlı", level: "C2" },
  { id: 509, english: "Admonish", turkish: "Azarlamak / Uyarmak", level: "C2" },
  { id: 510, english: "Adroit", turkish: "Becerikli / Usta", level: "C2" },
  { id: 511, english: "Adulation", turkish: "Aşırı övgü / Dalkavukluk", level: "C2" },
  { id: 512, english: "Aesthetic", turkish: "Estetik", level: "C2" },
  { id: 513, english: "Affable", turkish: "Sıcakkanlı / Cana yakın", level: "C2" },
  { id: 514, english: "Alacrity", turkish: "Çeviklik / İsteklilik", level: "C2" },
  { id: 515, english: "Alleviate", turkish: "Hafifletmek / Yatıştırmak", level: "C2" },
  { id: 516, english: "Amalgamate", turkish: "Birleştirmek / Kaynaştırmak", level: "C2" },
  { id: 517, english: "Ameliorate", turkish: "İyileştirmek / Düzeltmek", level: "C2" },
  { id: 518, english: "Amenable", turkish: "Uysal / Razı", level: "C2" },
  { id: 519, english: "Anachronistic", turkish: "Çağdışı / Zamanına uymayan", level: "C2" },
  { id: 520, english: "Anomaly", turkish: "Anormallik / Sapma", level: "C2" },
  { id: 521, english: "Antipathy", turkish: "Antipati / Nefret", level: "C2" },
  { id: 522, english: "Apathy", turkish: "Kayıtsızlık / İlgisizlik", level: "C2" },
  { id: 523, english: "Apocryphal", turkish: "Şüpheli / Uydurma (hikaye)", level: "C2" },
  { id: 524, english: "Appease", turkish: "Yatıştırmak / Teskin etmek", level: "C2" },
  { id: 525, english: "Arcane", turkish: "Gizemli / Sır dolu", level: "C2" },
  { id: 526, english: "Arduous", turkish: "Zorlu / Zahmetli", level: "C2" },
  { id: 527, english: "Ascetic", turkish: "Çileci / Zahit", level: "C2" },
  { id: 528, english: "Assiduous", turkish: "Çalışkan / Gayretli", level: "C2" },
  { id: 529, english: "Assuage", turkish: "Yatıştırmak / Dindirmek", level: "C2" },
  { id: 530, english: "Audacious", turkish: "Cüretkar / Gözü pek", level: "C2" },
  { id: 531, english: "Auspicious", turkish: "Uğurlu / Hayırlı", level: "C2" },
  { id: 532, english: "Austere", turkish: "Sade / Sert / Çetin", level: "C2" },
  { id: 533, english: "Avarice", turkish: "Açgözlülük / Hırs", level: "C2" },
  { id: 534, english: "Banal", turkish: "Bayağı / Sıradan", level: "C2" },
  { id: 535, english: "Bellicose", turkish: "Savaşçı / Kavgacı", level: "C2" },
  { id: 536, english: "Belligerent", turkish: "Savaşan / Kavgacı", level: "C2" },
  { id: 537, english: "Benevolent", turkish: "Hayırsever / İyiliksever", level: "C2" },
  { id: 538, english: "Blatant", turkish: "Apaçık / Bariz (olumsuz)", level: "C2" },
  { id: 539, english: "Boorish", turkish: "Kaba / Yontulmamış", level: "C2" },
  { id: 540, english: "Brazen", turkish: "Yüzsüz / Arsız", level: "C2" },
  { id: 541, english: "Bucolic", turkish: "Kırsal / pastoral", level: "C2" },
  { id: 542, english: "Cacophony", turkish: "Kakofoni / Uyumsuz sesler", level: "C2" },
  { id: 543, english: "Cajole", turkish: "Tatlı dille kandırmak / Yaltaklanmak", level: "C2" },
  { id: 544, english: "Callous", turkish: "Nasırlaşmış / Duygusuz", level: "C2" },
  { id: 545, english: "Calumny", turkish: "İftira / Karalama", level: "C2" },
  { id: 546, english: "Capitulate", turkish: "Teslim olmak / Boyun eğmek", level: "C2" },
  { id: 547, english: "Capricious", turkish: "Kaprisli / Değişken", level: "C2" },
  { id: 548, english: "Castigate", turkish: "Azarlamak / Cezalandırmak", level: "C2" },
  { id: 549, english: "Caustic", turkish: "Yakıcı / İğneleyici (söz)", level: "C2" },
  { id: 550, english: "Censure", turkish: "Kınama / Ayıplama", level: "C2" },
  { id: 551, english: "Chicanery", turkish: "Hile / Dalavere", level: "C2" },
  { id: 552, english: "Circumlocution", turkish: "Dolaylı anlatım / Lafı dolandırma", level: "C2" },
  { id: 553, english: "Circumspect", turkish: "Tedbirli / Dikkatli", level: "C2" },
  { id: 554, english: "Clandestine", turkish: "Gizli / Kaçak", level: "C2" },
  { id: 555, english: "Clemency", turkish: "Merhamet / Hoşgörü", level: "C2" },
  { id: 556, english: "Coalesce", turkish: "Birleşmek / Kaynaşmak", level: "C2" },
  { id: 557, english: "Cogent", turkish: "İkna edici / Mantıklı", level: "C2" },
  { id: 558, english: "Cognizant", turkish: "Farkında / Bilinçli", level: "C2" },
  { id: 559, english: "Complacent", turkish: "Kendinden memnun / Gaflet içinde", level: "C2" },
  { id: 560, english: "Concomitant", turkish: "Beraberinde gelen / Eşlik eden", level: "C2" },
  { id: 561, english: "Conduit", turkish: "Kanal / Boru / Vasıta", level: "C2" },
  { id: 562, english: "Conflagration", turkish: "Büyük yangın", level: "C2" },
  { id: 563, english: "Congenial", turkish: "Cana yakın / Uyumlu", level: "C2" },
  { id: 564, english: "Conjecture", turkish: "Tahmin / Varsayım", level: "C2" },
  { id: 565, english: "Connive", turkish: "Göz yummak / Suç ortaklığı yapmak", level: "C2" },
  { id: 566, english: "Connoisseur", turkish: "Uzman / Gurme", level: "C2" },
  { id: 567, english: "Consecrate", turkish: "Kutsamak / Adamak", level: "C2" },
  { id: 568, english: "Contentious", turkish: "Tartışmalı / Kavgacı", level: "C2" },
  { id: 569, english: "Contrite", turkish: "Pişman / Tövbekar", level: "C2" },
  { id: 570, english: "Contumacious", turkish: "İnatçı / Asi", level: "C2" },
  { id: 571, english: "Conundrum", turkish: "Muamma / Bilmece", level: "C2" },
  { id: 572, english: "Copious", turkish: "Bol / Bereketli", level: "C2" },
  { id: 573, english: "Corpulent", turkish: "Şişman / İri yarı", level: "C2" },
  { id: 574, english: "Corroborate", turkish: "Doğrulamak / Teyit etmek", level: "C2" },
  { id: 575, english: "Cosmopolitan", turkish: "Kozmopolit / Evrensel", level: "C2" },
  { id: 576, english: "Countenance", turkish: "Yüz ifadesi / Onaylamak", level: "C2" },
  { id: 577, english: "Covert", turkish: "Gizli / Örtülü", level: "C2" },
  { id: 578, english: "Credulous", turkish: "Saf / Her şeye inanan", level: "C2" },
  { id: 579, english: "Culpable", turkish: "Suçlu / Kusurlu", level: "C2" },
  { id: 580, english: "Cursory", turkish: "Yüzeysel / Gelişigüzel", level: "C2" },
  { id: 581, english: "Daunt", turkish: "Yıldırmak / Gözünü korkutmak", level: "C2" },
  { id: 582, english: "Dearth", turkish: "Kıtlık / Eksiklik", level: "C2" },
  { id: 583, english: "Debacle", turkish: "Fiyasko / Hezimet", level: "C2" },
  { id: 584, english: "Debilitate", turkish: "Zayıflatmak / Güçten düşürmek", level: "C2" },
  { id: 585, english: "Decorous", turkish: "Görgülü / Nazik", level: "C2" },
  { id: 586, english: "Defamation", turkish: "İftira / Karalama", level: "C2" },
  { id: 587, english: "Deference", turkish: "Saygı / Hürmet", level: "C2" },
  { id: 588, english: "Deleterious", turkish: "Zararlı / Sağlığa aykırı", level: "C2" },
  { id: 589, english: "Delineate", turkish: "Tasvir etmek / Betimlemek", level: "C2" },
  { id: 590, english: "Demagogue", turkish: "Demagog / Halk avcısı", level: "C2" },
  { id: 591, english: "Demur", turkish: "İtiraz etmek / Tereddüt etmek", level: "C2" },
  { id: 592, english: "Denigrate", turkish: "Kötülemek / Karalamak", level: "C2" },
  { id: 593, english: "Deprecate", turkish: "Karşı çıkmak / Kınamak", level: "C2" },
  { id: 594, english: "Deride", turkish: "Alay etmek / Küçümsemek", level: "C2" },
  { id: 595, english: "Desiccate", turkish: "Kurutmak / Suyunu çekmek", level: "C2" },
  { id: 596, english: "Desultory", turkish: "Gelişigüzel / Amaçsız", level: "C2" },
  { id: 597, english: "Diatribe", turkish: "Sert eleştiri / Suçlama", level: "C2" },
  { id: 598, english: "Diffident", turkish: "Çekingen / Utangaç", level: "C2" },
  { id: 599, english: "Dilatory", turkish: "Ağırkanlı / Oyalanan", level: "C2" },
  { id: 600, english: "Dilettante", turkish: "Amatör / Hevesli (sanatta)", level: "C2" }
];

export type LevelGroup = "A1-A2" | "B1-B2" | "C1-C2";

export const levelGroups: { name: LevelGroup; levels: (Word["level"])[] }[] = [
  { name: "A1-A2", levels: ["A1", "A2"] },
  { name: "B1-B2", levels: ["B1", "B2"] },
  { name: "C1-C2", levels: ["C1", "C2"] },
];
